name: Déploiement sur Alwaysdata

on:
  push:
    branches:
      - main  # Déclenche l'action uniquement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du code
        uses: actions/checkout@v3  # Récupère le code du dépôt GitHub

      - name: Connexion SSH et déploiement sur Alwaysdata
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "[✓] Connexion réussie sur Alwaysdata"
            cd $HOME/www/
            
            # Mise à jour du projet depuis GitHub
            if [ -d "mon-projet" ]; then
              cd mon-projet
              git pull origin main
            else
              git clone git@github.com:ton-utilisateur/ton-repo.git mon-projet
              cd mon-projet
            fi

            # Installation des dépendances si besoin
            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt --user
            fi

            # Redémarrage de Flask
            pkill -f flask || true  # Tue l'ancien processus Flask s'il existe
            nohup flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &

            echo "[✓] Déploiement terminé avec succès !"
